server:
  port: 8083
spring:
  application:
    name: api_microservice
  rabbitmq:
    host: localhost
    port: 5672
    username: test_rabbit
    password: test_rabbit
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
