version: '3'

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "test_rabbit"
      RABBITMQ_DEFAULT_PASS: "test_rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
    networks:
      - common

  mongo:
    restart: always
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - ./data/db:/var/micro-data/mongodb/data/db
    ports:
      - 27017:27017
    networks:
      - common

networks:
  common: