version: '3'

services:
  api_gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - common
  discovery:
    build:
      context: ms-discovery
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    networks:
      - common

  ms_api:
    build:
      context: ms-api
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    networks:
      - common

  ms_generation:
    build:
      context: ms-generation
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    networks:
      - common

  ms_persistence:
    build:
      context: ms-persistence
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    networks:
      - common

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "test_rabbit"
      RABBITMQ_DEFAULT_PASS: "test_rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
    networks:
      - common

  mongo:
    restart: always
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - ./data/db:/var/micro-data/mongodb/data/db
    ports:
      - 27017:27017
    networks:
      - common

networks:
  common:
    driver: bridge