server:
  port: 8080
spring:
  application:
    name: api_gateway
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
zuul:
  routes:
    generation:
      path: /generation/**
      serviceId: generation_microservice
    api:
      path: /api/**
      serviceId: api_microservice
#ribbon:
#  ReadTimeout: 30000
#  IsSecure: false