server:
  port: 8080
spring:
  application:
    name: api_gateway
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      default-zone: http://discovery:8761/eureka
zuul:
  routes:
    api:
      path: /api/**
      serviceId: api_microservice
ribbon:
  ReadTimeout: 10000
  IsSecure: false