server:
  port: 8080
spring:
  application:
    name: api_gateway
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
zuul:
  routes:
    api:
      path: /api/**
      serviceId: api_microservice
ribbon:
  ReadTimeout: 10000
  IsSecure: false