spring:
  application:
    name: persistence_microservice
  rabbitmq:
    host: localhost
    port: 5672
    username: test_rabbit
    password: test_rabbit
server:
  port: 8002
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      default-zone: http://discovery:8761/eureka

